// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangSach.Context;

#nullable disable

namespace QuanLyCuaHangSach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250226151947_Addtaikhoanvathongtin")]
    partial class Addtaikhoanvathongtin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangSach.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.HoaDonBan", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("HoaDonBan");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<int>("MaThongTinNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("ThongTinNguoiDungMaThongTinNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("ThongTinNguoiDungMaThongTinNguoiDung");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.KhoSach", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMat")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaKho", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("KhoSach");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaThongTinNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("ThongTinNguoiDungMaThongTinNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ThongTinNguoiDungMaThongTinNguoiDung");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuDatTruoc", b =>
                {
                    b.Property<int>("MaPhieuDatTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuDatTruoc"));

                    b.Property<int>("KhachHangMaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuDatTruoc");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("PhieuDatTruoc");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"));

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuTra"));

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuTra");

                    b.HasIndex("MaPhieuMuon")
                        .IsUnique();

                    b.ToTable("PhieuTra");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMuon")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<bool>("DaXacNhanEmail")
                        .HasColumnType("bit");

                    b.Property<string>("MaOTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoanNguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.ThongTinNguoiDung", b =>
                {
                    b.Property<int>("MaThongTinNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongTinNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongTinNguoiDung");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("ThongTinNguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.HoaDonBan", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSach.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.HoaDonBan", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.ThongTinNguoiDung", "ThongTinNguoiDung")
                        .WithMany()
                        .HasForeignKey("ThongTinNguoiDungMaThongTinNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongTinNguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.KhoSach", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.ThongTinNguoiDung", "ThongTinNguoiDung")
                        .WithMany()
                        .HasForeignKey("ThongTinNguoiDungMaThongTinNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongTinNguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuDatTruoc", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuMuon", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuMuon")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.PhieuTra", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.PhieuMuon", "PhieuMuon")
                        .WithOne()
                        .HasForeignKey("QuanLyCuaHangSach.Models.PhieuTra", "MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Sach", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("Sach")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSach.Models.TheLoai", "TheLoai")
                        .WithMany("Sach")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.ThongTinNguoiDung", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.TaiKhoanNguoiDung", "TaiKhoanNguoiDung")
                        .WithOne("ThongTinNguoiDung")
                        .HasForeignKey("QuanLyCuaHangSach.Models.ThongTinNguoiDung", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanNguoiDung");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.HoaDonBan", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.NhaCungCap", b =>
                {
                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Navigation("ThongTinNguoiDung")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.TheLoai", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
